### ISSUE TITLE
hacs 提示下载失败

### ISSUE THREAD

**Issue by caideone** [nexhome-org/nexhome-homeassistant-component#3]
Downloading nexhome-org/nexhome-homeassistant-component with version v1.1.0 failed with (Could not download, see log for details)
![Uploading 微信图片_20241010215343.png…]()

**Comment by linzh322** [comment]
图片查看不了，你是怎么下载的呢，目前建议通过点击readme的链接下载

**Comment by caideone** [comment]
hacs无法下载，然后击readme的链接下载。出现以下故障，有客户交流群吗
![微信图片_20241122141329](https://github.com/user-attachments/assets/d1b89d2d-05f8-4948-86c1-5207b713b72d)

**Comment by linzh322** [comment]
hacs还在pr中，暂时没有客户交流群，你这边能提供下日志吗

**Comment by caideone** [comment]
日志记录器: homeassistant.config_entries
来源: config_entries.py:635
首次出现: 11:26:02 (1 次总计出现)
上次记录: 11:26:02

Error setting up entry My Component for nexhome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1268, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1300, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/nexhome/number.py", line 33, in <module>
    class NexhomeInputNumber(NexhomeEntity, NumberEntity):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 397, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 369, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_native_value in subclass

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nexhome/__init__.py", line 14, in async_setup_entry
    await hass.async_create_task(hass.config_entries.async_forward_entry_setup(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2314, in async_forward_entry_setup
    result = await self._async_forward_entry_setup(entry, domain, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2345, in _async_forward_entry_setup
    await integration.async_get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1104, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1169, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1094, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1288, in _load_platform
    raise ImportError(
ImportError: Exception importing custom_components.nexhome.number

**Comment by linzh322** [comment]
好的，谢谢，再问下，您的HA是哪个版本的。看报错是number实体的问题，您可以尝试忽略掉再重新启动看看。
![6290b5af9ae55035d2ab957633135f4](https://github.com/user-attachments/assets/c7f92254-85d6-4d3d-8d00-edbefdbf302c)

**Comment by caideone** [comment]
Core
2024.11.2
Supervisor
2024.11.4
Operating System
13.2
Frontend
20241106.2

**Comment by linzh322** [comment]
你可以下载最新的插件解决你的问题
